"""initial migration

Revision ID: 47919c2f012e
Revises: 
Create Date: 2026-01-05 17:53:45.500535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '47919c2f012e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organize_code', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('file_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('transcription_content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audio_file_conversation_id'), 'audio_file', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_audio_file_created_at'), 'audio_file', ['created_at'], unique=False)
    op.create_index(op.f('ix_audio_file_id'), 'audio_file', ['id'], unique=False)
    op.create_index(op.f('ix_audio_file_organize_code'), 'audio_file', ['organize_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audio_file_organize_code'), table_name='audio_file')
    op.drop_index(op.f('ix_audio_file_id'), table_name='audio_file')
    op.drop_index(op.f('ix_audio_file_created_at'), table_name='audio_file')
    op.drop_index(op.f('ix_audio_file_conversation_id'), table_name='audio_file')
    op.drop_table('audio_file')
    # ### end Alembic commands ###
